name: 'test my project'
on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@v1
        name: 'setup node'
        with:
          dotnet-version: '5.0.x'