// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NJsonSchema;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Polygon.Infrastructure;

namespace Polygon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210201171645_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Polygon.Domain.Entities.FormSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<JsonSchema>("Schema")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("FormSchemas");
                });
#pragma warning restore 612, 618
        }
    }
}
