// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Polygon.Infrastructure;

namespace Polygon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210207150647_Migration6")]
    partial class Migration6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Polygon.Domain.Entities.FormData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("FormSchemaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ImportedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("FormSchemaId");

                    b.ToTable("FormData");
                });

            modelBuilder.Entity("Polygon.Domain.Entities.FormSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTimeOffset>("CreationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("FormSchemas");
                });

            modelBuilder.Entity("Polygon.Domain.Entities.FormData", b =>
                {
                    b.HasOne("Polygon.Domain.Entities.FormSchema", "FormSchema")
                        .WithMany("FormDatas")
                        .HasForeignKey("FormSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormSchema");
                });

            modelBuilder.Entity("Polygon.Domain.Entities.FormSchema", b =>
                {
                    b.Navigation("FormDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
