# Default values for infrastructure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fusionauth: 
  database: 
    host: infrastructure-postgresql
    user: postgres
    password: postgres
    root: 
      user: postgres
      password: postgres
  search: 
    engine: database 
  service:
    type: LoadBalancer 

postgresql:
  postgresqlPassword: postgres
  service: 
    type: LoadBalancer
    
elasticsearch:
  metrics: 
    enabled: true
  kibana: 
    service: 
      type: LoadBalancer
  global: 
    kibanaEnabled: true
    
jaeger:
  agent: 
    service: 
      type: NodePort
  provisionDataStore: 
    cassandra: false
  storage: 
    type: elasticsearch
    elasticsearch: 
      host: infrastructure-elasticsearch-master
      port: 9200
      usePassword: false
  query:
    service: 
      type: NodePort

grafana:
  service:
    port: 9080
    type: LoadBalancer
  persistence: 
    enabled: true
  adminPassword: admin

prometheus: 
  serverFiles: 
    prometheus.yml:
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: [ 'localhost:9090' ]
        - job_name: 'polygon'
          scrape_interval: 5s
          metrics_path: /metrics-text
          static_configs:
            - targets: [ 'host.docker.internal:5000' ]
        
        
        
    
